version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/hopeBench
      - KEYCLOAK_AUTHORIZATION_URL=http://keycloak:8080/realms/hopeBench/protocol/openid-connect/auth
      - KEYCLOAK_TOKEN_URL=http://keycloak:8080/realms/hopeBench/protocol/openid-connect/token
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=hopeBench
      - KEYCLOAK_CLIENT_FRONT_ID=hopeBench-front
    volumes:
      - ./backend:/app/backend
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: hopeBench
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command: start-dev --import-realm
    volumes:
      - ./docker/keycloak:/opt/keycloak/data