"""Add constant values to DB

Revision ID: 432aaeb8d23c
Revises: e4e47a14e663
Create Date: 2024-09-26 16:11:25.191153

"""
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '432aaeb8d23c'
down_revision: Union[str, None] = 'e4e47a14e663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add Computer
    computers = [
        {"id_computer": "23", "model": "Portable Talan (ou portable d\u00e9j\u00e0 en votre possession)"},
        {"id_computer": "24", "model": "Portable remis \u00e0 neuf\/reconditionn\u00e9"},
        {"id_computer": "25", "model": "Autre mod\u00e8le \/ Je ne sais pas"},
        {"id_computer": "57", "model": "Acer Chromebook C740"},
        {"id_computer": "178", "model": "Chromebook 3100"}, {"id_computer": "189", "model": "Chromebook 3100 2-in-1"},
        {"id_computer": "124", "model": "Chromebook 3400"}, {"id_computer": "83", "model": "Chromebook 5190"},
        {"id_computer": "168", "model": "Chromebook 5190 2-in-1"}, {"id_computer": "440", "model": "Ducati 5"},
        {"id_computer": "406", "model": "Flex 5G-14, Yoga 5G-14"}, {"id_computer": "58", "model": "Google Pixelbook"},
        {"id_computer": "55", "model": "Google Pixelbook GO"},
        {"id_computer": "61", "model": "HP Chromebook 11 G7 Education Edition"},
        {"id_computer": "60", "model": "HP Chromebook Enterprise 14A G5"},
        {"id_computer": "56", "model": "HP Chromebook Enterprise x360 14E G1"},
        {"id_computer": "59", "model": "HP Chromebook x360 11 G2 Education Edition"},
        {"id_computer": "54", "model": "HP Chromebook x360 14 G1"}, {"id_computer": "297", "model": "IdeaPad 1 11"},
        {"id_computer": "296", "model": "IdeaPad 1 11 AMD"}, {"id_computer": "302", "model": "IdeaPad 1 14"},
        {"id_computer": "298", "model": "IdeaPad 1 14 AMD"}, {"id_computer": "299", "model": "Ideapad 1 14IAU7"},
        {"id_computer": "300", "model": "Ideapad 1 14IGL7"}, {"id_computer": "301", "model": "Ideapad 1 14IJL7"},
        {"id_computer": "303", "model": "Ideapad 1 15IJL7"}, {"id_computer": "304", "model": "Ideapad 110-14IBR"},
        {"id_computer": "307", "model": "Ideapad 110-15, TianYi 310-15"},
        {"id_computer": "305", "model": "Ideapad 110-15ACL"},
        {"id_computer": "306", "model": "Ideapad 110-15IBR"}, {"id_computer": "308", "model": "Ideapad 110-17"},
        {"id_computer": "309", "model": "Ideapad 120S-11"}, {"id_computer": "310", "model": "Ideapad 130-14"},
        {"id_computer": "311", "model": "Ideapad 130-15 AMD"}, {"id_computer": "312", "model": "Ideapad 130-15 Intel"},
        {"id_computer": "315", "model": "IdeaPad 3 14 ITL05"}, {"id_computer": "316", "model": "IdeaPad 3 14 ITL6"},
        {"id_computer": "317", "model": "IdeaPad 3 14, V14 Gen 2-AMD"},
        {"id_computer": "313", "model": "IdeaPad 3 14ADA6"},
        {"id_computer": "314", "model": "IdeaPad 3 14IAU7"}, {"id_computer": "321", "model": "IdeaPad 3 15 ITL05"},
        {"id_computer": "322", "model": "IdeaPad 3 15 ITL6"},
        {"id_computer": "324", "model": "IdeaPad 3 15, V15 Gen 2-AMD"},
        {"id_computer": "319", "model": "IdeaPad 3 15ADA6"}, {"id_computer": "320", "model": "IdeaPad 3 15IAU7"},
        {"id_computer": "326", "model": "IdeaPad 3 17, V17"}, {"id_computer": "325", "model": "IdeaPad 3 17ADA6"},
        {"id_computer": "329", "model": "Ideapad 3 Chrome 14M836"},
        {"id_computer": "331", "model": "IdeaPad 3 Chrome 15IJL6"},
        {"id_computer": "332", "model": "IdeaPad 3 Chrome 15IJL6"},
        {"id_computer": "328", "model": "IdeaPad 3 Chromebook 11"},
        {"id_computer": "327", "model": "IdeaPad 3 Chromebook 11 AMD"},
        {"id_computer": "330", "model": "IdeaPad 3 Chromebook 14"},
        {"id_computer": "318", "model": "IdeaPad 3-14, V14"}, {"id_computer": "323", "model": "IdeaPad 3-15, V15"},
        {"id_computer": "334", "model": "Ideapad 310 Touch-15ISK"},
        {"id_computer": "333", "model": "Ideapad 310-14ISK"},
        {"id_computer": "335", "model": "Ideapad 310-15ISK"}, {"id_computer": "336", "model": "Ideapad 310S-15IKB"},
        {"id_computer": "337", "model": "Ideapad 320-14"},
        {"id_computer": "338", "model": "Ideapad 320-15, 320-15 Touch, 520-15"},
        {"id_computer": "339", "model": "Ideapad 320-17"}, {"id_computer": "340", "model": "Ideapad 320S-13"},
        {"id_computer": "341", "model": "Ideapad 320S-14"}, {"id_computer": "342", "model": "IdeaPad 320S-15"},
        {"id_computer": "343", "model": "Ideapad 330-14"}, {"id_computer": "344", "model": "Ideapad 330-15, B330-15"},
        {"id_computer": "345", "model": "Ideapad 330-17"}, {"id_computer": "346", "model": "Ideapad 330S-14"},
        {"id_computer": "347", "model": "Ideapad 330S-15"}, {"id_computer": "349", "model": "IdeaPad 4G 14, 5G 14"},
        {"id_computer": "348", "model": "IdeaPad 4G LTE 14"},
        {"id_computer": "351", "model": "IdeaPad 5 14 ACL05, XiaoXin"},
        {"id_computer": "352", "model": "IdeaPad 5 14 ACL05, XiaoXin"},
        {"id_computer": "355", "model": "IdeaPad 5 14, Xiao Xin"},
        {"id_computer": "354", "model": "IdeaPad 5 14, Xiao Xin Air-14 2020"},
        {"id_computer": "356", "model": "IdeaPad 5 14, Xiao Xin, Xiao Xin Air 14 2021"},
        {"id_computer": "350", "model": "Ideapad 5 14ABA7"}, {"id_computer": "353", "model": "Ideapad 5 14IAL7"},
        {"id_computer": "360", "model": "IdeaPad 5 15, XiaoXin, XiaoXin"},
        {"id_computer": "357", "model": "IdeaPad 5 15ALC05, XiaoXin, XiaoXin Air"},
        {"id_computer": "358", "model": "IdeaPad 5 15IAL7, XiaoXin 15 IAL7"},
        {"id_computer": "361", "model": "IdeaPad 5 Chrome 14ITL6"},
        {"id_computer": "363", "model": "IdeaPad 5 Pro 14 CAN6"},
        {"id_computer": "366", "model": "IdeaPad 5 Pro 14 ITL6,  Xiaoxin pro 14+"},
        {"id_computer": "364", "model": "IdeaPad 5 Pro 14ARH7"},
        {"id_computer": "365", "model": "IdeaPad 5 Pro 14IAP7"},
        {"id_computer": "367", "model": "IdeaPad 5 Pro 16 AMD"},
        {"id_computer": "368", "model": "IdeaPad 5 Pro 16ARH7"},
        {"id_computer": "369", "model": "IdeaPad 5 Pro 16IAH7"},
        {"id_computer": "370", "model": "IdeaPad 5 Pro 16IHU6"}, {"id_computer": "359", "model": "IdeaPad 5-15"},
        {"id_computer": "371", "model": "Ideapad 510-15ISK"}, {"id_computer": "372", "model": "Ideapad 510S-13IKB"},
        {"id_computer": "373", "model": "Ideapad 510S-14ISK"}, {"id_computer": "374", "model": "Ideapad 520-15"},
        {"id_computer": "375", "model": "Ideapad 520S-14"}, {"id_computer": "647", "model": "Ideapad 530S-14"},
        {"id_computer": "376", "model": "Ideapad 530S-14, XiaoXin Air 14"},
        {"id_computer": "648", "model": "Ideapad 530S-15"},
        {"id_computer": "377", "model": "Ideapad 700-17ISK"}, {"id_computer": "378", "model": "Ideapad 710S Plus-13"},
        {"id_computer": "379", "model": "Ideapad 720-15"}, {"id_computer": "380", "model": "Ideapad 720S-13"},
        {"id_computer": "381", "model": "Ideapad 720S-14"},
        {"id_computer": "382", "model": "Ideapad 720S-15, 720S-15 Touch, V730-15"},
        {"id_computer": "383", "model": "IdeaPad 730S-13, Yoga S730-13 2nd Gen"},
        {"id_computer": "386", "model": "IdeaPad C340-14, FLEX-14"},
        {"id_computer": "385", "model": "IdeaPad C340-14, Flex-14 2nd Gen"},
        {"id_computer": "387", "model": "IdeaPad C340-15, FLEX-15"},
        {"id_computer": "649", "model": "IdeaPad C340-15, FLEX-15"},
        {"id_computer": "389", "model": "Ideapad D330-10"}, {"id_computer": "388", "model": "IdeaPad D330-10 2nd Gen"},
        {"id_computer": "441", "model": "IdeaPad Flex 14"}, {"id_computer": "393", "model": "IdeaPad Flex 3 11"},
        {"id_computer": "392", "model": "IdeaPad Flex 3 11 AMD"},
        {"id_computer": "395", "model": "Ideapad Flex 3 CB 11M836"},
        {"id_computer": "396", "model": "IdeaPad Flex 3 Chromebook 11"},
        {"id_computer": "397", "model": "IdeaPad Flex 3 Chromebook 11"},
        {"id_computer": "394", "model": "IdeaPad Flex 3 Chromebook 11IJL6"},
        {"id_computer": "399", "model": "IdeaPad Flex 5 14"},
        {"id_computer": "398", "model": "IdeaPad Flex 5 14ALC7,  ABA7"},
        {"id_computer": "362", "model": "IdeaPad Flex 5 14IAU7"},
        {"id_computer": "401", "model": "IdeaPad Flex 5 15"}, {"id_computer": "402", "model": "IdeaPad Flex 5 15"},
        {"id_computer": "400", "model": "IdeaPad Flex 5 15 ALC05"},
        {"id_computer": "403", "model": "IdeaPad Flex 5 16ALC7,  ABA7"},
        {"id_computer": "405", "model": "IdeaPad Flex 5 Chromebook 13"},
        {"id_computer": "404", "model": "IdeaPad Flex 5 Chromebook 13ITL6"},
        {"id_computer": "411", "model": "IdeaPad Gaming 3 15"},
        {"id_computer": "407", "model": "IdeaPad Gaming 3 15ACH6"},
        {"id_computer": "408", "model": "IdeaPad Gaming 3 15ARH7"},
        {"id_computer": "409", "model": "IdeaPad Gaming 3 15IAH7"},
        {"id_computer": "410", "model": "IdeaPad Gaming 3 15IHU6"},
        {"id_computer": "413", "model": "IdeaPad Gaming 3 16ARH7"},
        {"id_computer": "414", "model": "IdeaPad Gaming 3 16IAH7"},
        {"id_computer": "412", "model": "IdeaPad Gaming 3-15, IdeaPad Creator 5-15"},
        {"id_computer": "415", "model": "IdeaPad L3 15"},
        {"id_computer": "416", "model": "IdeaPad L340-15 Gaming"},
        {"id_computer": "417", "model": "Ideapad L340-15, L340-15 Touch"},
        {"id_computer": "419", "model": "Ideapad L340-17"}, {"id_computer": "418", "model": "IdeaPad L340-17 Gaming"},
        {"id_computer": "420", "model": "Ideapad S130-11"}, {"id_computer": "421", "model": "Ideapad S130-14"},
        {"id_computer": "422", "model": "IdeaPad S145-14, V14"},
        {"id_computer": "423", "model": "IdeaPad S145-15, V15"},
        {"id_computer": "424", "model": "IdeaPad S340-13"}, {"id_computer": "425", "model": "IdeaPad S340-14"},
        {"id_computer": "426", "model": "Ideapad S340-14, S340-14 Touch"},
        {"id_computer": "427", "model": "IdeaPad S340-15 Series, XiaoXin-15"},
        {"id_computer": "428", "model": "Ideapad S340-15, S340-15 Touch"},
        {"id_computer": "429", "model": "Ideapad S530-13"},
        {"id_computer": "430", "model": "IdeaPad S540-13, Xiao Xin Pro 13 13s 2021"},
        {"id_computer": "431", "model": "IdeaPad S540-13, Xiao Xin Pro 13 13s 2021"},
        {"id_computer": "432", "model": "IdeaPad S540-13, Xiao Xin Pro 13 2020, Xiao Xin Pro 13s 2020"},
        {"id_computer": "433", "model": "IdeaPad S540-14 Series 2nd Gen, YangTian Air-14"},
        {"id_computer": "434", "model": "IdeaPad S540-14, S540-14 Touch"},
        {"id_computer": "435", "model": "IdeaPad S540-15"},
        {"id_computer": "650", "model": "IdeaPad S540-15 GTX"},
        {"id_computer": "436", "model": "IdeaPad S550-15, XiaoXinAir 15 2021"},
        {"id_computer": "437", "model": "Ideapad S740-14, Yoga S740-14, XiaoXin Pro-14"},
        {"id_computer": "439", "model": "IdeaPad S940-14, Yoga S940-14"},
        {"id_computer": "121", "model": "Inspiron 13 5320"},
        {"id_computer": "122", "model": "Inspiron 14 5420"}, {"id_computer": "94", "model": "Inspiron 14 5425"},
        {"id_computer": "76", "model": "Inspiron 14 7420 2-in-1"},
        {"id_computer": "63", "model": "Inspiron 14 7425 2-in-1"},
        {"id_computer": "67", "model": "Inspiron 14 Plus 7420"}, {"id_computer": "64", "model": "Inspiron 16 5620"},
        {"id_computer": "65", "model": "Inspiron 16 5625"}, {"id_computer": "66", "model": "Inspiron 16 7620 2-in-1"},
        {"id_computer": "68", "model": "Inspiron 16 Plus 7620"},
        {"id_computer": "390", "model": "IP Duet 5 Chromebook 13Q7C6"},
        {"id_computer": "391", "model": "IP Duet 5 Chromebook 13Q7C6"},
        {"id_computer": "254", "model": "Latitude 3120"},
        {"id_computer": "255", "model": "Latitude 3120 2-in-1"}, {"id_computer": "257", "model": "Latitude 3150"},
        {"id_computer": "263", "model": "Latitude 3160"}, {"id_computer": "230", "model": "Latitude 3180"},
        {"id_computer": "237", "model": "Latitude 3189"}, {"id_computer": "228", "model": "Latitude 3190"},
        {"id_computer": "218", "model": "Latitude 3190 2-In-1"}, {"id_computer": "206", "model": "Latitude 3300"},
        {"id_computer": "205", "model": "Latitude 3301"}, {"id_computer": "204", "model": "Latitude 3310"},
        {"id_computer": "203", "model": "Latitude 3310 2-in-1"}, {"id_computer": "201", "model": "Latitude 3320"},
        {"id_computer": "199", "model": "Latitude 3330"}, {"id_computer": "200", "model": "Latitude 3330 2-in-1"},
        {"id_computer": "198", "model": "Latitude 3350"}, {"id_computer": "197", "model": "Latitude 3380"},
        {"id_computer": "196", "model": "Latitude 3390 2-in-1"}, {"id_computer": "195", "model": "Latitude 3400"},
        {"id_computer": "194", "model": "Latitude 3410"}, {"id_computer": "193", "model": "Latitude 3420"},
        {"id_computer": "192", "model": "Latitude 3430"}, {"id_computer": "208", "model": "Latitude 3460"},
        {"id_computer": "209", "model": "Latitude 3470"}, {"id_computer": "210", "model": "Latitude 3480"},
        {"id_computer": "226", "model": "Latitude 3490"}, {"id_computer": "224", "model": "Latitude 3500"},
        {"id_computer": "223", "model": "Latitude 3510"}, {"id_computer": "222", "model": "Latitude 3520"},
        {"id_computer": "225", "model": "Latitude 3530"}, {"id_computer": "221", "model": "Latitude 3550"},
        {"id_computer": "220", "model": "Latitude 3560"}, {"id_computer": "154", "model": "Latitude 3570"},
        {"id_computer": "153", "model": "Latitude 3580"}, {"id_computer": "152", "model": "Latitude 3590"},
        {"id_computer": "148", "model": "Latitude 5250"}, {"id_computer": "147", "model": "Latitude 5280"},
        {"id_computer": "146", "model": "Latitude 5285 2-in-1"},
        {"id_computer": "145", "model": "Latitude 5289 2-in-1"},
        {"id_computer": "143", "model": "Latitude 5290"}, {"id_computer": "142", "model": "Latitude 5290 2-in-1"},
        {"id_computer": "139", "model": "Latitude 5300"}, {"id_computer": "137", "model": "Latitude 5300 2-in-1"},
        {"id_computer": "138", "model": "Latitude 5300 2-in-1 Chromebook"},
        {"id_computer": "136", "model": "Latitude 5310"},
        {"id_computer": "135", "model": "Latitude 5310 2-in-1"}, {"id_computer": "134", "model": "Latitude 5320"},
        {"id_computer": "132", "model": "Latitude 5320 2-in-1"}, {"id_computer": "141", "model": "Latitude 5330"},
        {"id_computer": "155", "model": "Latitude 5330 2-in-1"}, {"id_computer": "130", "model": "Latitude 5400"},
        {"id_computer": "129", "model": "Latitude 5400 Chromebook"}, {"id_computer": "128", "model": "Latitude 5401"},
        {"id_computer": "127", "model": "Latitude 5410"}, {"id_computer": "140", "model": "Latitude 5411"},
        {"id_computer": "156", "model": "Latitude 5420"}, {"id_computer": "181", "model": "Latitude 5421"},
        {"id_computer": "264", "model": "Latitude 5430"}, {"id_computer": "131", "model": "Latitude 5430 Rugged"},
        {"id_computer": "265", "model": "Latitude 5431"}, {"id_computer": "186", "model": "Latitude 5450"},
        {"id_computer": "185", "model": "Latitude 5480"}, {"id_computer": "184", "model": "Latitude 5490"},
        {"id_computer": "183", "model": "Latitude 5491"}, {"id_computer": "182", "model": "Latitude 5495"},
        {"id_computer": "180", "model": "Latitude 5500"}, {"id_computer": "179", "model": "Latitude 5501"},
        {"id_computer": "177", "model": "Latitude 5510"}, {"id_computer": "176", "model": "Latitude 5511"},
        {"id_computer": "175", "model": "Latitude 5520"}, {"id_computer": "174", "model": "Latitude 5521"},
        {"id_computer": "249", "model": "Latitude 5530"}, {"id_computer": "250", "model": "Latitude 5531"},
        {"id_computer": "173", "model": "Latitude 5550"}, {"id_computer": "172", "model": "Latitude 5580"},
        {"id_computer": "171", "model": "Latitude 5590"}, {"id_computer": "170", "model": "Latitude 5591"},
        {"id_computer": "162", "model": "Latitude 7200 2 -in-1"},
        {"id_computer": "161", "model": "Latitude 7210 2-in-1"},
        {"id_computer": "160", "model": "Latitude 7220 Rugged Extreme"},
        {"id_computer": "214", "model": "Latitude 7280"},
        {"id_computer": "159", "model": "Latitude 7285"}, {"id_computer": "188", "model": "Latitude 7290"},
        {"id_computer": "169", "model": "Latitude 7300"},
        {"id_computer": "167", "model": "Latitude 7300 25th Anniversary Edition"},
        {"id_computer": "125", "model": "Latitude 7310"}, {"id_computer": "108", "model": "Latitude 7310 2-in-1"},
        {"id_computer": "90", "model": "Latitude 7320"}, {"id_computer": "88", "model": "Latitude 7320 2-IN-1"},
        {"id_computer": "89", "model": "Latitude 7320 Detachable"}, {"id_computer": "252", "model": "Latitude 7330"},
        {"id_computer": "251", "model": "Latitude 7330 2 -in-1"},
        {"id_computer": "244", "model": "Latitude 7330 Rugged Extreme"},
        {"id_computer": "87", "model": "Latitude 7350"}, {"id_computer": "86", "model": "Latitude 7370"},
        {"id_computer": "85", "model": "Latitude 7380"}, {"id_computer": "84", "model": "Latitude 7389 2-in-1"},
        {"id_computer": "215", "model": "Latitude 7390"}, {"id_computer": "82", "model": "Latitude 7390 2-in-1"},
        {"id_computer": "81", "model": "Latitude 7400"}, {"id_computer": "80", "model": "Latitude 7400 2-in-1"},
        {"id_computer": "79", "model": "Latitude 7410"}, {"id_computer": "91", "model": "Latitude 7410 2-in-1"},
        {"id_computer": "77", "model": "Latitude 7410 2-in-1 Chromebook Enterprise"},
        {"id_computer": "78", "model": "Latitude 7410 Chromebook Enterprise"},
        {"id_computer": "72", "model": "Latitude 7420"},
        {"id_computer": "93", "model": "Latitude 7420 2-in-1"}, {"id_computer": "253", "model": "Latitude 7430"},
        {"id_computer": "266", "model": "Latitude 7430 2-in-1"}, {"id_computer": "107", "model": "Latitude 7480"},
        {"id_computer": "216", "model": "Latitude 7490"}, {"id_computer": "261", "model": "Latitude 7520"},
        {"id_computer": "258", "model": "Latitude 7530"}, {"id_computer": "233", "model": "Latitude 9330"},
        {"id_computer": "262", "model": "Latitude 9410"}, {"id_computer": "256", "model": "Latitude 9410 2-IN-1"},
        {"id_computer": "202", "model": "Latitude 9420"}, {"id_computer": "207", "model": "Latitude 9420 2 -in-1"},
        {"id_computer": "259", "model": "Latitude 9430"}, {"id_computer": "260", "model": "Latitude 9430 2-in-1"},
        {"id_computer": "229", "model": "Latitude 9510"}, {"id_computer": "144", "model": "Latitude 9510 2-in-1"},
        {"id_computer": "133", "model": "Latitude 9520"}, {"id_computer": "187", "model": "Latitude 9520 2-in-1"},
        {"id_computer": "151", "model": "Latitude E5270"}, {"id_computer": "150", "model": "Latitude E5470"},
        {"id_computer": "149", "model": "Latitude E5570"}, {"id_computer": "166", "model": "Latitude E7250"},
        {"id_computer": "165", "model": "Latitude E7270"}, {"id_computer": "164", "model": "Latitude E7450"},
        {"id_computer": "163", "model": "Latitude E7470"}, {"id_computer": "157", "model": "Latitude Rugged 5420"},
        {"id_computer": "158", "model": "Latitude Rugged 5424"},
        {"id_computer": "52", "model": "Lenovo 100e Chromebook (2nd Gen)"},
        {"id_computer": "49", "model": "Lenovo 14e Chromebook"},
        {"id_computer": "51", "model": "Lenovo 300e Chromebook (2nd Gen)"},
        {"id_computer": "50", "model": "Lenovo 500e Chromebook (2nd Gen)"},
        {"id_computer": "53", "model": "Lenovo YOGA Chromebook C630"},
        {"id_computer": "46", "model": "Macbook 12\u0022"},
        {"id_computer": "45", "model": "Macbook Air 13\u0022 (Non-Retina)"},
        {"id_computer": "43", "model": "Macbook Air 13\u0022 (Retina, 2019)"},
        {"id_computer": "44", "model": "Macbook Air 13\u0022 (Retina, Thunderbolt)"},
        {"id_computer": "40", "model": "Macbook Air 13\u0022 Intel (2020) 256GB SSD"},
        {"id_computer": "39", "model": "Macbook Air 13\u0022 Intel (2020) 512GB SSD"},
        {"id_computer": "42", "model": "Macbook Air 13\u0022 M1 (2020) 256GB SSD"},
        {"id_computer": "41", "model": "Macbook Air 13\u0022 M1 (2020) 512GB SSD"},
        {"id_computer": "48", "model": "Macbook Air 13.6\u0022 M2 (2022) 256GB SSD"},
        {"id_computer": "33", "model": "Macbook Air 13.6\u0022 M2 (2022) 512GB SSD"},
        {"id_computer": "37", "model": "Macbook Pro 13\u0022 (2019)"},
        {"id_computer": "38", "model": "Macbook Pro 13\u0022 (Skylake and newer)"},
        {"id_computer": "34", "model": "Macbook Pro 13\u0022 M1 (2020) 256GB SSD"},
        {"id_computer": "26", "model": "Macbook Pro 13\u0022 M1 (2020) 512GB SSD"},
        {"id_computer": "30", "model": "Macbook Pro 14\u0022 Intel (2021) 256GB SSD"},
        {"id_computer": "29", "model": "Macbook Pro 14\u0022 Intel (2021) 512GB SSD"},
        {"id_computer": "32", "model": "Macbook Pro 14\u0022 M1 Pro (2021) 256GB SSD"},
        {"id_computer": "31", "model": "Macbook Pro 14\u0022 M1 Pro (2021) 512GB SSD"},
        {"id_computer": "47", "model": "Macbook Pro 15\u0022 (Skylake and newer)"},
        {"id_computer": "35", "model": "Macbook Pro 16\u0022 (2019)"},
        {"id_computer": "36", "model": "Macbook Pro 16\u0022 M1 Max (2021) 1TB SSD"},
        {"id_computer": "27", "model": "Macbook Pro 16\u0022 M1 Pro (2021) 1TB SSD"},
        {"id_computer": "28", "model": "Macbook Pro 16\u0022 M1 Pro (2021) 512GB SSD"},
        {"id_computer": "95", "model": "Precision 3470"},
        {"id_computer": "101", "model": "Precision 3510"}, {"id_computer": "100", "model": "Precision 3520"},
        {"id_computer": "99", "model": "Precision 3530"}, {"id_computer": "98", "model": "Precision 3540"},
        {"id_computer": "97", "model": "Precision 3541"}, {"id_computer": "96", "model": "Precision 3550"},
        {"id_computer": "62", "model": "Precision 3551"}, {"id_computer": "92", "model": "Precision 3560"},
        {"id_computer": "126", "model": "Precision 3561"}, {"id_computer": "190", "model": "Precision 3570"},
        {"id_computer": "227", "model": "Precision 3571"}, {"id_computer": "243", "model": "Precision 5470"},
        {"id_computer": "191", "model": "Precision 5520"}, {"id_computer": "217", "model": "Precision 5530"},
        {"id_computer": "245", "model": "Precision 5540"}, {"id_computer": "241", "model": "Precision 5550"},
        {"id_computer": "240", "model": "Precision 5560"}, {"id_computer": "242", "model": "Precision 5570"},
        {"id_computer": "239", "model": "Precision 5760"}, {"id_computer": "102", "model": "Precision 5770"},
        {"id_computer": "238", "model": "Precision 7520"}, {"id_computer": "234", "model": "Precision 7530"},
        {"id_computer": "232", "model": "Precision 7540"}, {"id_computer": "235", "model": "Precision 7550"},
        {"id_computer": "236", "model": "Precision 7560"}, {"id_computer": "103", "model": "Precision 7670"},
        {"id_computer": "219", "model": "Precision 7720"}, {"id_computer": "248", "model": "Precision 7730"},
        {"id_computer": "231", "model": "Precision 7740"}, {"id_computer": "246", "model": "Precision 7750"},
        {"id_computer": "247", "model": "Precision 7760"}, {"id_computer": "104", "model": "Precision 7770"},
        {"id_computer": "284", "model": "Surface Book"}, {"id_computer": "283", "model": "Surface Book 2 (13.5 inch)"},
        {"id_computer": "282", "model": "Surface Book 2 (15 inch)"},
        {"id_computer": "280", "model": "Surface Book 3 (13.5 inch)"},
        {"id_computer": "281", "model": "Surface Book 3 (15 inch)"}, {"id_computer": "293", "model": "Surface Go"},
        {"id_computer": "292", "model": "Surface Go 2"}, {"id_computer": "291", "model": "Surface Go 3"},
        {"id_computer": "294", "model": "Surface Laptop"}, {"id_computer": "279", "model": "Surface Laptop 2"},
        {"id_computer": "267", "model": "Surface Laptop 3 (Alcantara, 13.5 inch)"},
        {"id_computer": "269", "model": "Surface Laptop 3 (Alcantara, 15 inch)"},
        {"id_computer": "268", "model": "Surface Laptop 3 (Metal, 13.5 inch)"},
        {"id_computer": "270", "model": "Surface Laptop 3 (Metal, 15 inch)"},
        {"id_computer": "271", "model": "Surface Laptop 4 (Alcantara, 13.5 inch)"},
        {"id_computer": "278", "model": "Surface Laptop 4 (Metal, 13.5 inch)"},
        {"id_computer": "273", "model": "Surface Laptop 4 (Metal, 15 inch)"},
        {"id_computer": "276", "model": "Surface Laptop 5 13.5"},
        {"id_computer": "277", "model": "Surface Laptop 5 15"}, {"id_computer": "295", "model": "Surface Pro 4"},
        {"id_computer": "289", "model": "Surface Pro 5"}, {"id_computer": "288", "model": "Surface Pro 6"},
        {"id_computer": "287", "model": "Surface Pro 7"}, {"id_computer": "286", "model": "Surface Pro 7+"},
        {"id_computer": "285", "model": "Surface Pro 8"}, {"id_computer": "275", "model": "Surface Pro 9 Intel\/Wifi"},
        {"id_computer": "274", "model": "Surface Pro 9 SQ3 5G"}, {"id_computer": "290", "model": "Surface Pro X"},
        {"id_computer": "272", "model": "Surface Studio 2+"}, {"id_computer": "459", "model": "ThinkBook 13s"},
        {"id_computer": "455", "model": "ThinkBook 13s 2nd Gen"},
        {"id_computer": "454", "model": "ThinkBook 13s 2nd Gen AMD"},
        {"id_computer": "456", "model": "ThinkBook 13s G3 ACN"},
        {"id_computer": "457", "model": "ThinkBook 13s G4 ARB"},
        {"id_computer": "458", "model": "ThinkBook 13s G4 IAP"},
        {"id_computer": "460", "model": "ThinkBook 13x G2 IAP"},
        {"id_computer": "461", "model": "ThinkBook 13x ITG"}, {"id_computer": "443", "model": "ThinkBook 14"},
        {"id_computer": "462", "model": "ThinkBook 14 2nd Gen AMD, Prestigio 6 14, Zhaoyang K4e"},
        {"id_computer": "463", "model": "ThinkBook 14 2nd Gen, Prestige 6 14, Zhaoyang E4, K4e"},
        {"id_computer": "464", "model": "ThinkBook 14 3rd Gen ACL"},
        {"id_computer": "465", "model": "ThinkBook 14 G3 ITL"},
        {"id_computer": "468", "model": "ThinkBook 14 G4 IAP"}, {"id_computer": "466", "model": "Thinkbook 14 G4+ ARA"},
        {"id_computer": "467", "model": "ThinkBook 14 G4+ IAP"},
        {"id_computer": "469", "model": "ThinkBook 14p G2 ACH"},
        {"id_computer": "470", "model": "ThinkBook 14p G3 ARH"}, {"id_computer": "474", "model": "ThinkBook 14s"},
        {"id_computer": "472", "model": "ThinkBook 14s 2nd Gen"},
        {"id_computer": "471", "model": "ThinkBook 14s 2nd Gen AMD"},
        {"id_computer": "473", "model": "ThinkBook 14s AMD"},
        {"id_computer": "475", "model": "Thinkbook 14s Yoga 2nd Gen-Intel"},
        {"id_computer": "476", "model": "ThinkBook 14s Yoga G2 IAP"}, {"id_computer": "444", "model": "ThinkBook 15"},
        {"id_computer": "477", "model": "ThinkBook 15 2nd Gen AMD, Prestigio 6 15"},
        {"id_computer": "478", "model": "ThinkBook 15 2nd Gen, Prestige 6 15,  Zhaoyang E5"},
        {"id_computer": "479", "model": "ThinkBook 15 3rd Gen ACL"},
        {"id_computer": "480", "model": "ThinkBook 15 G3 ITL"},
        {"id_computer": "481", "model": "ThinkBook 15 G4 ABA,  Zhaoyang E5-ABA"},
        {"id_computer": "482", "model": "ThinkBook 15 G4 IAP,  Zhaoyang K5e IAP"},
        {"id_computer": "484", "model": "ThinkBook 15p"},
        {"id_computer": "483", "model": "ThinkBook 15p G2 ITH"},
        {"id_computer": "485", "model": "Thinkbook 16 G4+ ARA"},
        {"id_computer": "486", "model": "ThinkBook 16 G4+ IAP"},
        {"id_computer": "487", "model": "ThinkBook 16p G2 ACH"},
        {"id_computer": "488", "model": "ThinkBook 16p G3 ARH"},
        {"id_computer": "489", "model": "ThinkBook 16p NX ARH"},
        {"id_computer": "492", "model": "ThinkBook Plus"}, {"id_computer": "490", "model": "ThinkBook Plus G2 ITG"},
        {"id_computer": "491", "model": "ThinkBook Plus G3 IAP"}, {"id_computer": "445", "model": "ThinkPad 10"},
        {"id_computer": "493", "model": "ThinkPad 10 (2nd Gen)"},
        {"id_computer": "494", "model": "ThinkPad 11e 3rd Gen, ThinkPad Yoga 11e 3rd Gen"},
        {"id_computer": "446", "model": "ThinkPad 11e Chromebook 3rd Gen, ThinkPad Yoga 11e Chromebook 3rd Gen"},
        {"id_computer": "496", "model": "ThinkPad 11e Chromebook 4th Gen, ThinkPad Yoga 11e Chromebook 4th Gen"},
        {"id_computer": "497", "model": "ThinkPad 11e Yoga 6th Gen"},
        {"id_computer": "447", "model": "ThinkPad 11e, ThinkPad Yoga 11e"},
        {"id_computer": "500", "model": "ThinkPad 13"},
        {"id_computer": "498", "model": "ThinkPad 13 2nd Gen, ThinkPad S2 2nd Gen"},
        {"id_computer": "499", "model": "ThinkPad 13, ThinkPad S2"}, {"id_computer": "501", "model": "ThinkPad 25"},
        {"id_computer": "448", "model": "ThinkPad 8"}, {"id_computer": "502", "model": "ThinkPad A275"},
        {"id_computer": "503", "model": "ThinkPad A285"}, {"id_computer": "504", "model": "ThinkPad A475"},
        {"id_computer": "505", "model": "ThinkPad A485"},
        {"id_computer": "506", "model": "ThinkPad C13 Yoga Chromebook"},
        {"id_computer": "654", "model": "ThinkPad C14 Gen 1 Chromebook"},
        {"id_computer": "508", "model": "ThinkPad E14 2nd Gen"},
        {"id_computer": "509", "model": "ThinkPad E14 Gen 3"},
        {"id_computer": "510", "model": "ThinkPad E14 Gen 4 AMD"},
        {"id_computer": "512", "model": "ThinkPad E14 Gen 4 Intel"},
        {"id_computer": "511", "model": "ThinkPad E14, R14 2nd Gen"},
        {"id_computer": "513", "model": "ThinkPad E14, ThinkPad R14, ThinkPad S3 Gen2"},
        {"id_computer": "518", "model": "ThinkPad E15"},
        {"id_computer": "514", "model": "ThinkPad E15 2nd Gen"}, {"id_computer": "515", "model": "ThinkPad E15 Gen 3"},
        {"id_computer": "517", "model": "ThinkPad E15 Gen 4"},
        {"id_computer": "516", "model": "ThinkPad E15 Gen 4 AMD"},
        {"id_computer": "537", "model": "ThinkPad E450"}, {"id_computer": "538", "model": "ThinkPad E455"},
        {"id_computer": "519", "model": "ThinkPad E460"}, {"id_computer": "520", "model": "ThinkPad E465"},
        {"id_computer": "521", "model": "ThinkPad E475"},
        {"id_computer": "651", "model": "ThinkPad E480, ThinkPad R480"},
        {"id_computer": "523", "model": "ThinkPad E490, R490"}, {"id_computer": "522", "model": "ThinkPad E490s"},
        {"id_computer": "524", "model": "ThinkPad E495"}, {"id_computer": "525", "model": "ThinkPad E550"},
        {"id_computer": "526", "model": "ThinkPad E560"},
        {"id_computer": "527", "model": "ThinkPad E560p, ThinkPad S5"},
        {"id_computer": "528", "model": "ThinkPad E565"}, {"id_computer": "530", "model": "ThinkPad E575"},
        {"id_computer": "531", "model": "ThinkPad E580"}, {"id_computer": "532", "model": "ThinkPad E585"},
        {"id_computer": "533", "model": "ThinkPad E590, R590"}, {"id_computer": "534", "model": "ThinkPad E595"},
        {"id_computer": "449", "model": "ThinkPad Edge E145"}, {"id_computer": "535", "model": "ThinkPad Edge E431"},
        {"id_computer": "450", "model": "ThinkPad Edge E440"}, {"id_computer": "536", "model": "ThinkPad Edge E445"},
        {"id_computer": "539", "model": "ThinkPad Edge E531"}, {"id_computer": "540", "model": "ThinkPad Edge E540"},
        {"id_computer": "541", "model": "ThinkPad Edge E545"}, {"id_computer": "542", "model": "ThinkPad Helix"},
        {"id_computer": "543", "model": "ThinkPad K14 Gen 1 AMD"},
        {"id_computer": "544", "model": "ThinkPad K14 Gen 1 Intel"},
        {"id_computer": "655", "model": "ThinkPad L13 Gen 3 AMD"},
        {"id_computer": "656", "model": "ThinkPad L13 Gen 3 Intel"},
        {"id_computer": "545",
         "model": "ThinkPad L13 Yoga Gen 2, ThinkPad L13 Gen 2, ThinkPad S2 Yoga Gen 6, ThinkPad S2 Gen 6 (AMD) "},
        {"id_computer": "657", "model": "ThinkPad L13 Yoga Gen 3 AMD"},
        {"id_computer": "658", "model": "ThinkPad L13 Yoga Gen 3 Intel"},
        {"id_computer": "546", "model": "ThinkPad L13, L13 Yoga 2nd Gen, ThinkPad S2, S2 Yoga 6th Gen"},
        {"id_computer": "547", "model": "ThinkPad L13, S2 5th Gen, L13 Yoga, S2 Yoga 5th Gen"},
        {"id_computer": "548", "model": "ThinkPad L14 Gen 2 AMD"},
        {"id_computer": "549", "model": "ThinkPad L14 Gen 2 Intel"},
        {"id_computer": "659", "model": "ThinkPad L14 Gen 3 AMD"},
        {"id_computer": "660", "model": "ThinkPad L14 Gen 3 Intel"},
        {"id_computer": "550", "model": "ThinkPad L15 Gen 2 AMD"},
        {"id_computer": "551", "model": "ThinkPad L15 Gen 2 Intel"},
        {"id_computer": "661", "model": "ThinkPad L15 Gen 3 AMD"},
        {"id_computer": "662", "model": "ThinkPad L15 Gen 3 Intel"},
        {"id_computer": "642", "model": "ThinkPad L380 Yoga, ThinkPad S2 Yoga 3rd Gen"},
        {"id_computer": "552", "model": "ThinkPad L390, S2 Yoga 4th Gen"},
        {"id_computer": "553", "model": "ThinkPad L440"},
        {"id_computer": "554", "model": "ThinkPad L450"}, {"id_computer": "555", "model": "ThinkPad L470"},
        {"id_computer": "556", "model": "ThinkPad L480"}, {"id_computer": "557", "model": "ThinkPad L490"},
        {"id_computer": "558", "model": "ThinkPad L560"}, {"id_computer": "559", "model": "ThinkPad L570"},
        {"id_computer": "560", "model": "ThinkPad L580"}, {"id_computer": "561", "model": "ThinkPad L590"},
        {"id_computer": "570", "model": "ThinkPad P1 2nd Gen, X1 Extreme"},
        {"id_computer": "562", "model": "ThinkPad P1 Gen 4, ThinkPad X1 Extreme Gen 4 "},
        {"id_computer": "663", "model": "ThinkPad P1 Gen 5 "},
        {"id_computer": "571", "model": "ThinkPad P1, ThinkPad X1 Extreme"},
        {"id_computer": "563", "model": "ThinkPad P14s"}, {"id_computer": "664", "model": "ThinkPad P14s Gen 3 AMD"},
        {"id_computer": "665", "model": "ThinkPad P14s Gen 3 Intel"},
        {"id_computer": "567", "model": "ThinkPad P15 Gen 2, ThinkPad T15g Gen 2"},
        {"id_computer": "568", "model": "ThinkPad P15, ThinkPad T15g"},
        {"id_computer": "566", "model": "ThinkPad P15v Gen 1, ThinkPad T15p Gen 1"},
        {"id_computer": "666", "model": "ThinkPad P15v Gen 3 AMD "},
        {"id_computer": "667", "model": "ThinkPad P15v Gen 3 Intel "},
        {"id_computer": "668", "model": "ThinkPad P15v Gen 3 Intel "},
        {"id_computer": "669", "model": "ThinkPad P16 Gen 1 "},
        {"id_computer": "670", "model": "ThinkPad P16s Gen 1 AMD"},
        {"id_computer": "671", "model": "ThinkPad P16s Gen 1 Intel"},
        {"id_computer": "569", "model": "ThinkPad P17 Gen 2"}, {"id_computer": "572", "model": "ThinkPad P50"},
        {"id_computer": "573", "model": "ThinkPad P51"}, {"id_computer": "574", "model": "ThinkPad P52"},
        {"id_computer": "575", "model": "ThinkPad P53"}, {"id_computer": "576", "model": "ThinkPad P70"},
        {"id_computer": "577", "model": "ThinkPad P71"}, {"id_computer": "578", "model": "ThinkPad P72"},
        {"id_computer": "579", "model": "ThinkPad P73"}, {"id_computer": "583", "model": "ThinkPad S1 Yoga"},
        {"id_computer": "582", "model": "ThinkPad S1 Yoga 4th Gen, X380 Yoga"},
        {"id_computer": "584", "model": "ThinkPad S3 Yoga 14"},
        {"id_computer": "585", "model": "ThinkPad S3, ThinkPad Yoga 460, ThinkPad Yoga 14"},
        {"id_computer": "529", "model": "ThinkPad S5 2nd Generation"},
        {"id_computer": "590", "model": "ThinkPad T14 Gen 2, ThinkPad P14s Gen 2"},
        {"id_computer": "672", "model": "ThinkPad T14 Gen 3 AMD"},
        {"id_computer": "673", "model": "ThinkPad T14 Gen 3 Intel "},
        {"id_computer": "591", "model": "ThinkPad T14, ThinkPad P14s"},
        {"id_computer": "589", "model": "ThinkPad T14s 2nd Gen"},
        {"id_computer": "588", "model": "ThinkPad T14s 2nd Gen Intel"},
        {"id_computer": "586", "model": "ThinkPad T14s Gen 2 AMD"},
        {"id_computer": "587", "model": "ThinkPad T14s Gen 2 AMD"},
        {"id_computer": "674", "model": "ThinkPad T14s Gen 3 AMD"},
        {"id_computer": "675", "model": "ThinkPad T14s Gen 3 Intel"},
        {"id_computer": "592", "model": "ThinkPad T15 Gen 2, ThinkPad P15s Gen 2"},
        {"id_computer": "593", "model": "ThinkPad T15, ThinkPad P15s"},
        {"id_computer": "564", "model": "ThinkPad T15p Gen 2 Intel"},
        {"id_computer": "565", "model": "ThinkPad T15p Gen 2 Intel"},
        {"id_computer": "676", "model": "ThinkPad T16 Gen 1 AMD"},
        {"id_computer": "677", "model": "ThinkPad T16 Gen 1 Intel"}, {"id_computer": "594", "model": "ThinkPad T440"},
        {"id_computer": "595", "model": "ThinkPad T440s"}, {"id_computer": "596", "model": "ThinkPad T450"},
        {"id_computer": "597", "model": "ThinkPad T450s"}, {"id_computer": "598", "model": "ThinkPad T460"},
        {"id_computer": "599", "model": "ThinkPad T460s"}, {"id_computer": "600", "model": "ThinkPad T470"},
        {"id_computer": "601", "model": "ThinkPad T470p"}, {"id_computer": "602", "model": "ThinkPad T470s"},
        {"id_computer": "603", "model": "ThinkPad T480"}, {"id_computer": "604", "model": "ThinkPad T480s"},
        {"id_computer": "606", "model": "ThinkPad T490, ThinkP ad P43s"},
        {"id_computer": "605", "model": "ThinkPad T490s"},
        {"id_computer": "607", "model": "ThinkPad T495"}, {"id_computer": "608", "model": "ThinkPad T495s"},
        {"id_computer": "609", "model": "ThinkPad T540p"}, {"id_computer": "610", "model": "ThinkPad T550"},
        {"id_computer": "611", "model": "ThinkPad T560, P50s"}, {"id_computer": "612", "model": "ThinkPad T570,  P51s"},
        {"id_computer": "613", "model": "ThinkPad T580, ThinkPad P52s"},
        {"id_computer": "614", "model": "ThinkPad T590, ThinkPad P53s"},
        {"id_computer": "615", "model": "ThinkPad W540 "},
        {"id_computer": "621", "model": "ThinkPad X1 Carbon 5th Gen"},
        {"id_computer": "618", "model": "ThinkPad X1 Carbon Gen 1"},
        {"id_computer": "678", "model": "ThinkPad X1 Carbon Gen 10"},
        {"id_computer": "619", "model": "ThinkPad X1 Carbon Gen 3"},
        {"id_computer": "622", "model": "ThinkPad X1 Carbon Gen 6"},
        {"id_computer": "617", "model": "ThinkPad X1 Carbon Gen 8"},
        {"id_computer": "507", "model": "ThinkPad X1 Carbon Gen 9"},
        {"id_computer": "620", "model": "ThinkPad X1 Carbon, ThinkPad X1 Carbon 4th"},
        {"id_computer": "616", "model": "ThinkPad X1 Carbon, X1 Carbon LTE 7th Gen"},
        {"id_computer": "679", "model": "ThinkPad X1 Extreme Gen 5 "},
        {"id_computer": "680", "model": "ThinkPad X1 Fold 16 Gen 1"},
        {"id_computer": "623", "model": "ThinkPad X1 Nano"}, {"id_computer": "681", "model": "ThinkPad X1 Nano Gen 2"},
        {"id_computer": "624",
         "model": "ThinkPad X1 Titanium Gen 1, ThinkPad X1 Titanium Gen 1 LTE, ThinkPad X1 Titanium Gen 1 5G "},
        {"id_computer": "627", "model": "ThinkPad X1 Yoga"},
        {"id_computer": "628", "model": "ThinkPad X1 Yoga 2nd Gen"},
        {"id_computer": "625", "model": "ThinkPad X1 Yoga 3rd Gen"},
        {"id_computer": "626", "model": "ThinkPad X1 Yoga Gen 5"},
        {"id_computer": "629", "model": "ThinkPad X1 Yoga Gen 6"},
        {"id_computer": "682", "model": "ThinkPad X1 Yoga Gen 7"},
        {"id_computer": "652", "model": "ThinkPad X1 Yoga, X1 Yoga LTE 4th Gen"},
        {"id_computer": "630", "model": "ThinkPad X13 Gen 2"},
        {"id_computer": "631", "model": "ThinkPad X13 Gen 2 Intel"},
        {"id_computer": "683", "model": "ThinkPad X13 Gen 3 AMD"},
        {"id_computer": "684", "model": "ThinkPad X13 Gen 3 Intel"},
        {"id_computer": "632", "model": "ThinkPad X13 Intel Gen 1"},
        {"id_computer": "634", "model": "ThinkPad X13 Yoga"},
        {"id_computer": "633", "model": "ThinkPad X13 Yoga Gen 2"},
        {"id_computer": "685", "model": "ThinkPad X13 Yoga Gen 3"},
        {"id_computer": "686", "model": "ThinkPad X13s Gen 1"},
        {"id_computer": "635", "model": "ThinkPad X240 "}, {"id_computer": "636", "model": "ThinkPad X240s"},
        {"id_computer": "637", "model": "ThinkPad X250"}, {"id_computer": "638", "model": "ThinkPad X260"},
        {"id_computer": "639", "model": "ThinkPad X270"}, {"id_computer": "640", "model": "ThinkPad X280"},
        {"id_computer": "641", "model": "ThinkPad X390"}, {"id_computer": "653", "model": "ThinkPad X390 Yoga"},
        {"id_computer": "495", "model": "ThinkPad Yoga 11e 5th Gen, 11e 5th Gen"},
        {"id_computer": "580", "model": "ThinkPad Yoga 260,ThinkPad S1(2nd \nGeneration) "},
        {"id_computer": "581", "model": "ThinkPad Yoga 370, ThinkPad S1(3rd Generation)"},
        {"id_computer": "687", "model": "ThinkPad Z13 Gen 1"}, {"id_computer": "688", "model": "ThinkPad Z16 Gen 1"},
        {"id_computer": "451", "model": "V17 G3 IAP"}, {"id_computer": "452", "model": "V17 G3 IAP"},
        {"id_computer": "69", "model": "Vostro 15 3510"}, {"id_computer": "70", "model": "Vostro 15 3515"},
        {"id_computer": "71", "model": "Vostro 5320"}, {"id_computer": "73", "model": "Vostro 5620"},
        {"id_computer": "74", "model": "Vostro 5625"},
        {"id_computer": "75", "model": "Vostro 7620"}, {"id_computer": "119", "model": "XPS 13 7390"},
        {"id_computer": "118", "model": "XPS 13 9300"},
        {"id_computer": "117", "model": "XPS 13 9310"}, {"id_computer": "116", "model": "XPS 13 9310 2-in-1"},
        {"id_computer": "115", "model": "XPS 13 9360"}, {"id_computer": "114", "model": "XPS 13 9365 2 -In-1"},
        {"id_computer": "211", "model": "XPS 13 9370"}, {"id_computer": "113", "model": "XPS 13 9380"},
        {"id_computer": "109", "model": "XPS 15 9500"}, {"id_computer": "106", "model": "XPS 15 9510"},
        {"id_computer": "123", "model": "XPS 15 9520"}, {"id_computer": "212", "model": "XPS 15 9560"},
        {"id_computer": "213", "model": "XPS 15 9570"}, {"id_computer": "105", "model": "XPS 17 9710"},
        {"id_computer": "112", "model": "XPS 9315"},
        {"id_computer": "111", "model": "XPS 9315 2-in-1"}, {"id_computer": "110", "model": "XPS 9320"},
        {"id_computer": "120", "model": "XPS 9720"},
        {"id_computer": "384", "model": "Yoga S730-13, Ideapad 730S-13"},
        {"id_computer": "438", "model": "Yoga S740-15, IdeaPad S740-15, S740-15 Touch"},
        {"id_computer": "453", "model": "Yoga Slim 7 13"},
        {"id_computer": "442", "model": "Yoga Slim 7 Carbon 13"},
        {"id_computer": "644", "model": "Yoga Slim 7 Carbon 13IAP7"},
        {"id_computer": "645", "model": "Yoga Slim 7 Carbon 14ACN6"},
        {"id_computer": "646", "model": "Yoga Slim 7 Carbon 14ACN6"},
        {"id_computer": "643", "model": "Yoga Slim 7 Pro 14IAP7, Slim 7"}
    ]  # Scraped from HOPE on 26/09/2024

    computers_db = [{"id_computer": uuid4(), "model": computer["model"]} for computer in computers]
    op.bulk_insert(
        sa.table(
            'computers',
            sa.column('id_computer', sa.UUID),
            sa.column('model', sa.String)
        ),
        computers_db
    )

    # Add Phones
    phones = [{"id_phone": "689", "model": "Smartphone Talan (ou smartphone d\u00e9j\u00e0 en votre possession)"},
              {"id_phone": "690", "model": "Smartphone remis \u00e0 neuf\/reconditionn\u00e9"},
              {"id_phone": "691", "model": "Autre mod\u00e8le \/ Je ne sais pas"},
              {"id_phone": "720", "model": "Galaxy A12"}, {"id_phone": "714", "model": "Galaxy M23"},
              {"id_phone": "713", "model": "Galaxy M33"}, {"id_phone": "712", "model": "Galaxy M53"},
              {"id_phone": "723", "model": "Galaxy Note20 Ultra"}, {"id_phone": "719", "model": "Galaxy S20 FE"},
              {"id_phone": "718", "model": "Galaxy S21 FE"}, {"id_phone": "717", "model": "Galaxy S22"},
              {"id_phone": "715", "model": "Galaxy S22 Ultra"}, {"id_phone": "716", "model": "Galaxy S22+"},
              {"id_phone": "721", "model": "Galaxy Z Flip3"}, {"id_phone": "722", "model": "Galaxy Z Fold3"},
              {"id_phone": "698", "model": "iPhone 12"}, {"id_phone": "696", "model": "iPhone 13"},
              {"id_phone": "697", "model": "iPhone 13 mini"}, {"id_phone": "695", "model": "iPhone 14"},
              {"id_phone": "694", "model": "iPhone 14 Plus"}, {"id_phone": "693", "model": "iPhone 14 Pro"},
              {"id_phone": "692", "model": "iPhone 14 Pro Max"},
              {"id_phone": "699", "model": "iPhone SE (3rd generation)"}, {"id_phone": "706", "model": "Pixel 3a"},
              {"id_phone": "707", "model": "Pixel 3a XL"}, {"id_phone": "708", "model": "Pixel 4"},
              {"id_phone": "711", "model": "Pixel 4 XL"}, {"id_phone": "710", "model": "Pixel 4a"},
              {"id_phone": "709", "model": "Pixel 4a (5G)"}, {"id_phone": "700", "model": "Pixel 5a with 5G"},
              {"id_phone": "702", "model": "Pixel 6"}, {"id_phone": "701", "model": "Pixel 6 Pro"},
              {"id_phone": "703", "model": "Pixel 6a"}, {"id_phone": "705", "model": "Pixel 7"},
              {"id_phone": "704", "model": "Pixel 7 Pro"}]  # Scraped from HOPE on 26/09/2024

    phones_db = [{"id_phone": uuid4(), "model": phone["model"]} for phone in phones]

    op.bulk_insert(
        sa.table(
            'phones',
            sa.column('id_phone', sa.UUID),
            sa.column('model', sa.String)
        ),
        phones_db
    )

    # Add Transports
    transports = [
        {"id_transport": uuid4(), "transport_mode": "Avion"},
        {"id_transport": uuid4(), "transport_mode": "Bus"},
        {"id_transport": uuid4(), "transport_mode": "Métro"},
        {"id_transport": uuid4(), "transport_mode": "RER ou Transilien"},
        {"id_transport": uuid4(), "transport_mode": "TGV"},
        {"id_transport": uuid4(), "transport_mode": "Train Intercités"},
        {"id_transport": uuid4(), "transport_mode": "Vélo (ou trottinette) à assistance électrique"},
        {"id_transport": uuid4(), "transport_mode": "Vélo ou marche"},
        {"id_transport": uuid4(), "transport_mode": "Voiture (électrique)"},
        {"id_transport": uuid4(), "transport_mode": "Voiture (thermique)"},
    ]  # Manually added from HOPE on 26/09/2024

    op.bulk_insert(
        sa.table(
            'transports',
            sa.column('id_transport', sa.UUID),
            sa.column('transport_mode', sa.String)
        ),
        transports
    )

    # Add Compute providers
    compute_providers = [{"id": "1044", "name": "Amazon Web Services",
                          "children": [{"id": "1129", "name": "ap-east-1"}, {"id": "1135", "name": "ap-northeast-1"},
                                       {"id": "1132", "name": "ap-northeast-2"},
                                       {"id": "1131", "name": "ap-northeast-3"}, {"id": "1130", "name": "ap-south-1"},
                                       {"id": "1133", "name": "ap-southeast-1"},
                                       {"id": "1134", "name": "ap-southeast-2"}, {"id": "1136", "name": "ca-central-1"},
                                       {"id": "1137", "name": "cn-north-1"}, {"id": "1138", "name": "cn-northwest-1"},
                                       {"id": "1139", "name": "eu-central-1"}, {"id": "1143", "name": "eu-north-1"},
                                       {"id": "1140", "name": "eu-west-1"}, {"id": "1141", "name": "eu-west-2"},
                                       {"id": "1142", "name": "eu-west-3"}, {"id": "1144", "name": "sa-east-1"},
                                       {"id": "1126", "name": "us-east-1"}, {"id": "1125", "name": "us-east-2"},
                                       {"id": "1145", "name": "us-gov-east-1"}, {"id": "1146", "name": "us-gov-west-1"},
                                       {"id": "1127", "name": "us-west-1"}, {"id": "1128", "name": "us-west-2"}]},
                         {"id": "1067", "name": "Azure", "children": [{"id": "1175", "name": "Australia Central"},
                                                                      {"id": "1176", "name": "Australia Central 2"},
                                                                      {"id": "1160", "name": "Australia East"},
                                                                      {"id": "1161", "name": "Australia South East"},
                                                                      {"id": "1159", "name": "Brazil South"},
                                                                      {"id": "1165", "name": "Canada Central"},
                                                                      {"id": "1166", "name": "Canada East"},
                                                                      {"id": "1163", "name": "Central India"},
                                                                      {"id": "1149", "name": "Central US"},
                                                                      {"id": "1147", "name": "East Asia"},
                                                                      {"id": "1150", "name": "East US"},
                                                                      {"id": "1151", "name": "East US 2"},
                                                                      {"id": "1173", "name": "France Central"},
                                                                      {"id": "1174", "name": "France South"},
                                                                      {"id": "1158", "name": "Japan East"},
                                                                      {"id": "1157", "name": "Japan West"},
                                                                      {"id": "1171", "name": "Korea Central"},
                                                                      {"id": "1172", "name": "Korea South"},
                                                                      {"id": "1153", "name": "North Central US"},
                                                                      {"id": "1155", "name": "North Europe"},
                                                                      {"id": "1177", "name": "South Africa North"},
                                                                      {"id": "1178", "name": "South Africa West"},
                                                                      {"id": "1154", "name": "South Central US"},
                                                                      {"id": "1148", "name": "South East Asia"},
                                                                      {"id": "1162", "name": "South India"},
                                                                      {"id": "1167", "name": "UK South"},
                                                                      {"id": "1168", "name": "UK West"},
                                                                      {"id": "1169", "name": "West Central US"},
                                                                      {"id": "1156", "name": "West Europe"},
                                                                      {"id": "1164", "name": "West India"},
                                                                      {"id": "1152", "name": "West US"},
                                                                      {"id": "1170", "name": "West US 2"}]},
                         {"id": "1023", "name": "Google Cloud Platform",
                          "children": [{"id": "1105", "name": "asia-east1"}, {"id": "1106", "name": "asia-east2"},
                                       {"id": "1107", "name": "asia-northeast1"},
                                       {"id": "1108", "name": "asia-northeast2"}, {"id": "1109", "name": "asia-south1"},
                                       {"id": "1110", "name": "asia-southeast1"},
                                       {"id": "1111", "name": "australia-southeast1"},
                                       {"id": "1112", "name": "europe-north1"}, {"id": "1113", "name": "europe-west1"},
                                       {"id": "1114", "name": "europe-west2"}, {"id": "1115", "name": "europe-west3"},
                                       {"id": "1116", "name": "europe-west4"}, {"id": "1117", "name": "europe-west6"},
                                       {"id": "1118", "name": "northamerica-northeast1"},
                                       {"id": "1119", "name": "southamerica-east1"},
                                       {"id": "1120", "name": "us-central1"}, {"id": "1121", "name": "us-east1"},
                                       {"id": "1122", "name": "us-east4"}, {"id": "1123", "name": "us-west1"},
                                       {"id": "1124", "name": "us-west2"}]},
                         {"id": "1100", "name": "OVHCloud",
                          "children": [
                              {"id": "1180", "name": "Beauharnois"},
                              {"id": "1179", "name": "Gravelines"}
                          ]},
                         {"id": "1103", "name": "Scaleway", "children": [{"id": "1181", "name": "France"}]}]
    # Scraped from HOPE on 26/09/2024

    compute_providers_db = [
        {"id_compute_provider": uuid4(), "name": provider["name"], "region": region["name"]}
        for provider in compute_providers for region in provider["children"]
    ]

    op.bulk_insert(
        sa.table(
            'compute_providers',
            sa.column('id_compute_provider', sa.UUID),
            sa.column('name', sa.String),
            sa.column('region', sa.String)
        ),
        compute_providers_db
    )

    # Add Storage providers
    storage_provider = [{"id": "904", "name": "Amazon S3",
                         "children": [
                             {"id": "911", "name": "af-south-1"}, {"id": "912", "name": "ap-east-1"},
                             {"id": "918", "name": "ap-northeast-1"}, {"id": "915", "name": "ap-northeast-2"},
                             {"id": "914", "name": "ap-northeast-3"}, {"id": "913", "name": "ap-south-1"},
                             {"id": "916", "name": "ap-southeast-1"}, {"id": "917", "name": "ap-southeast-2"},
                             {"id": "919", "name": "ca-central-1"}, {"id": "920", "name": "cn-north-1"},
                             {"id": "921", "name": "cn-northwest-1"}, {"id": "922", "name": "eu-central-1"},
                             {"id": "927", "name": "eu-north-1"}, {"id": "925", "name": "eu-south-1"},
                             {"id": "923", "name": "eu-west-1"}, {"id": "924", "name": "eu-west-2"},
                             {"id": "926", "name": "eu-west-3"}, {"id": "928", "name": "me-south-1"},
                             {"id": "929", "name": "sa-east-1"}, {"id": "905", "name": "us-east-1"},
                             {"id": "906", "name": "us-east-2"}, {"id": "909", "name": "us-gov-east-1"},
                             {"id": "910", "name": "us-gov-west-1"}, {"id": "907", "name": "us-west-1"},
                             {"id": "908", "name": "us-west-2"}]},
                        {"id": "930", "name": "Azure Blob",
                         "children": [
                             {"id": "945", "name": "Central India"},
                             {"id": "931", "name": "Central US"},
                             {"id": "941", "name": "East Asia"},
                             {"id": "932", "name": "East US"},
                             {"id": "933", "name": "East US 2"},
                             {"id": "934", "name": "East US 3"},
                             {"id": "935",
                              "name": "North Central US"},
                             {"id": "943", "name": "North Europe"},
                             {"id": "936",
                              "name": "South Central US"},
                             {"id": "946", "name": "South India"},
                             {"id": "942",
                              "name": "Southeast Asia"},
                             {"id": "948", "name": "UK South"},
                             {"id": "949", "name": "UK West"},
                             {"id": "937",
                              "name": "West Central US"},
                             {"id": "944", "name": "West Europe"},
                             {"id": "947", "name": "West India"},
                             {"id": "938", "name": "West US"},
                             {"id": "939", "name": "West US 2"},
                             {"id": "940", "name": "West US 3"}]},
                        {"id": "879", "name": "Google Cloud Storage",
                         "children": [{"id": "887", "name": "asia-east1"}, {"id": "888", "name": "asia-east2"},
                                      {"id": "889", "name": "asia-northeast1"},
                                      {"id": "890", "name": "asia-northeast2"},
                                      {"id": "891", "name": "asia-northeast3"}, {"id": "892", "name": "asia-south1"},
                                      {"id": "893", "name": "asia-southeast1"},
                                      {"id": "894", "name": "asia-southeast2"},
                                      {"id": "895", "name": "australia-southeast1"},
                                      {"id": "896", "name": "europe-north1"}, {"id": "897", "name": "europe-west1"},
                                      {"id": "898", "name": "europe-west2"}, {"id": "899", "name": "europe-west3"},
                                      {"id": "900", "name": "europe-west4"}, {"id": "901", "name": "europe-west6"},
                                      {"id": "902", "name": "northamerica-northeast1"},
                                      {"id": "903", "name": "southamerica-east1"}, {"id": "880", "name": "us-central1"},
                                      {"id": "881", "name": "us-east1"}, {"id": "882", "name": "us-east4"},
                                      {"id": "883", "name": "us-west1"}, {"id": "884", "name": "us-west2"},
                                      {"id": "885", "name": "us-west3"}, {"id": "886", "name": "us-west4"}]},
                        {"id": "950", "name": "OVHcloud",
                         "children": [{"id": "951", "name": "Beauharnois"}, {"id": "952", "name": "Gravelines"}]}]
    # Scraped from HOPE on 26/09/2024

    storage_provider_db = [
        {"id_storage_provider": uuid4(), "name": provider["name"], "region": region["name"]}
        for provider in storage_provider for region in provider["children"]
    ]

    op.bulk_insert(
        sa.table(
            'storage_providers',
            sa.column('id_storage_provider', sa.UUID),
            sa.column('name', sa.String),
            sa.column('region', sa.String)
        ),
        storage_provider_db
    )


def downgrade() -> None:
    op.execute("DELETE * FROM computers")
    op.execute("DELETE * FROM phones")
    op.execute("DELETE * FROM transports")
    op.execute("DELETE * FROM compute_providers")
    op.execute("DELETE * FROM storage_providers")
